name: Build Android APK with Buildozer
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Buildozer venv
        uses: actions/cache@v4
        with:
          path: .buildozervenv
          key: buildozer-venv-${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Build with Buildozer
        uses: ArtemSanya/buildozer-action@v1
        with:
          command: buildozer android debug
          repository_root: .
